### ISSUE TITLE
Brainstorming de fluxo de navegação

### ISSUE THREAD

**Issue by eokasta** [fmu-devmakers/vetechnarios#11]

**Comment by Vini4700** [comment]
Brainstorming para discussão sobre prioridades e melhor abordagem com o usuário. 

Qual estratégia usar para uma navegação mais intuitiva e simples, de forma eficaz com que o usuário sendo usuário comum em busca de atendimento veterinário ou sendo um veterinário cadastrado no projeto, possa visualizar e entender de forma transparente todo o fluxo e percurso que as informações percorreram o sistema.
